export const strings = {
  tab1: 'Stempeluhr',
  tab2: 'Feierabend-Rechner',
  clockIn: 'Einstempeln',
  clockOut: 'Ausstempeln',
  notePlaceholder: 'Notiz (optional)',
  overview: 'Übersicht',
  day: 'Tag',
  week: 'Woche',
  month: 'Monat',
  export: 'Exportieren',
  manualEntry: 'Manueller Eintrag',
  edit: 'Bearbeiten',
  delete: 'Löschen',
  confirmDelete: 'Wirklich löschen?',
  settings: 'Einstellungen',
  theme: 'Erscheinungsbild',
  themeSystem: 'System',
  themeLight: 'Hell',
  themeDark: 'Dunkel',
  dailyTarget: 'Tägliche Sollarbeitszeit',
  syncToggle: 'Google Drive Synchronisation',
  syncNow: 'Jetzt synchronisieren',
  signOut: 'Abmelden',
  jsonExport: 'Daten als JSON exportieren',
  jsonImport: 'Daten aus JSON importieren',
  calcClockIn: 'Einstempelzeit',
  calcBreak: 'Pausenlänge (min)',
  calcTarget: 'Sollarbeitszeit (min)',
  calcOvertimeMode: 'Überstunden hinzufügen',
  calcOvertimeInput: 'Zusätzliche Minuten',
  calcResult: 'Geplanter Feierabend',
  toastClockedIn: (time: string) => `Du bist eingestempelt seit ${time}`,
  toastForgottenClockOut: (date: string) =>
    `Letzter Eintrag vom ${date} ist noch offen. Korrigieren?`,
  toastSyncSuccess: 'Synchronisiert',
  toastSyncError: 'Synchronisation fehlgeschlagen',
  toastOffline: 'Offline — Änderungen werden später synchronisiert',
} as const
